# Generated by Django 5.2.11 on 2026-02-09 02:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Main Website', 'Landing Page'", max_length=255
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Expected origin domain", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "analytics_api_keys",
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "referrer_url",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                (
                    "referrer_domain",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("organic", "Organic Search"),
                            ("paid", "Paid Search"),
                            ("social", "Social Media"),
                            ("referral", "Referral"),
                            ("direct", "Direct"),
                            ("email", "Email"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "utm_campaign",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("utm_term", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "search_keywords",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("landing_page_url", models.CharField(db_index=True, max_length=2048)),
                (
                    "landing_page_title",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "browser_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("os_version", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "screen_resolution",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True, db_index=True, max_length=2, null=True
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("page_views_count", models.IntegerField(default=0)),
                ("events_count", models.IntegerField(default=0)),
                (
                    "duration_seconds",
                    models.IntegerField(default=0, help_text="Total session duration"),
                ),
                (
                    "is_bounce",
                    models.BooleanField(
                        default=False, help_text="Only viewed one page"
                    ),
                ),
                ("has_converted", models.BooleanField(db_index=True, default=False)),
                (
                    "conversion_event",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="analytics.apikey",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked when user logs in/registers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "analytics_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_url", models.CharField(db_index=True, max_length=2048)),
                ("page_title", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "page_path",
                    models.CharField(
                        blank=True, db_index=True, max_length=1024, null=True
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(
                        help_text="Order in session: 1st, 2nd, 3rd page viewed"
                    ),
                ),
                (
                    "previous_page_url",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "time_on_page_seconds",
                    models.IntegerField(
                        default=0, help_text="Calculated from next page view"
                    ),
                ),
                (
                    "scroll_depth_percent",
                    models.IntegerField(default=0, help_text="Max scroll percentage"),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="analytics.session",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_page_views",
                "ordering": ["session", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("cta_click", "CTA Click"),
                            ("button_click", "Button Click"),
                            ("link_click", "Link Click"),
                            ("form_submit", "Form Submit"),
                            ("form_start", "Form Started"),
                            ("download", "Download"),
                            ("video_play", "Video Play"),
                            ("video_complete", "Video Complete"),
                            ("scroll", "Scroll Event"),
                            ("outbound_click", "Outbound Link Click"),
                            ("search", "Site Search"),
                            ("conversion", "Conversion"),
                            ("custom", "Custom Event"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "event_category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g., 'Header CTA', 'Footer CTA', 'Pricing'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "event_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Download Brochure', 'Contact Sales'",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "event_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional numeric value (e.g., order amount)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("element_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "element_class",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "element_text",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("element_tag", models.CharField(blank=True, max_length=50, null=True)),
                ("page_url", models.CharField(max_length=2048)),
                ("page_path", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "time_since_page_load_ms",
                    models.IntegerField(help_text="Milliseconds since page loaded"),
                ),
                (
                    "time_since_session_start_seconds",
                    models.IntegerField(help_text="Seconds since session started"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional event-specific data",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "page_view",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analytics.pageview",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="analytics.session",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("sessions_count", models.IntegerField(default=0)),
                ("unique_users_count", models.IntegerField(default=0)),
                ("page_views_count", models.IntegerField(default=0)),
                ("events_count", models.IntegerField(default=0)),
                ("avg_session_duration_seconds", models.IntegerField(default=0)),
                (
                    "avg_pages_per_session",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "bounce_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("conversions_count", models.IntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("sources_breakdown", models.JSONField(blank=True, default=dict)),
                ("devices_breakdown", models.JSONField(blank=True, default=dict)),
                ("top_pages", models.JSONField(blank=True, default=dict)),
                ("top_landing_pages", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_metrics",
                        to="analytics.apikey",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_daily_metrics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["api_key", "date"],
                        name="analytics_d_api_key_1ab691_idx",
                    )
                ],
                "unique_together": {("api_key", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["created_at", "source"], name="analytics_s_created_e86fe5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["api_key", "created_at"], name="analytics_s_api_key_c4a00e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["user", "created_at"], name="analytics_s_user_id_db7e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["session", "sequence_number"],
                name="analytics_p_session_8debc1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["page_path", "viewed_at"], name="analytics_p_page_pa_ff1332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["viewed_at"], name="analytics_p_viewed__a5f8fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["session", "occurred_at"], name="analytics_e_session_a66e77_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type", "occurred_at"],
                name="analytics_e_event_t_7b4dc8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_category", "occurred_at"],
                name="analytics_e_event_c_22bf3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["page_path", "event_type"],
                name="analytics_e_page_pa_e148ec_idx",
            ),
        ),
    ]
