# Generated by Django 5.2.11 on 2026-02-09 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="User email when captured",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="DiagnosticResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnostic_name",
                    models.CharField(
                        help_text="Name of the diagnostic/quiz", max_length=255
                    ),
                ),
                (
                    "diagnostic_version",
                    models.CharField(
                        blank=True,
                        help_text="Version if you iterate on questions",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("answers", models.JSONField(help_text="All answers as JSON object")),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated score if applicable",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "result_category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Beginner', 'Advanced', 'High Risk'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Any extra data (time spent, partial completion, etc.)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When user started diagnostic", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When user completed diagnostic"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostics",
                        to="analytics.session",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_diagnostic_responses",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "completed_at"],
                        name="analytics_d_session_7815ba_idx",
                    ),
                    models.Index(
                        fields=["diagnostic_name", "completed_at"],
                        name="analytics_d_diagnos_0bf735_idx",
                    ),
                ],
            },
        ),
    ]
