# Generated by Django 5.2.11 on 2026-02-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_session_company_session_email_session_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="bot_score",
            field=models.IntegerField(
                default=0, help_text="Bot likelihood score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="is_suspected_bot",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Flagged as potential bot"
            ),
        ),
    ]
