# Generated by Django 5.2.11 on 2026-02-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_session_bot_score_session_is_suspected_bot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("cta_click", "CTA Click"),
                    ("button_click", "Button Click"),
                    ("link_click", "Link Click"),
                    ("form_submit", "Form Submit"),
                    ("form_start", "Form Started"),
                    ("download", "Download"),
                    ("video_play", "Video Play"),
                    ("video_complete", "Video Complete"),
                    ("scroll", "Scroll Event"),
                    ("outbound_click", "Outbound Link Click"),
                    ("search", "Site Search"),
                    ("conversion", "Conversion"),
                    ("custom", "Custom Event"),
                    ("diagnostic_started", "Diagnostic Started"),
                    ("diagnostic_question_shown", "Diagnostic Question Shown"),
                    ("diagnostic_step_completed", "Diagnostic Step Completed"),
                    ("diagnostic_contact_form_shown", "Diagnostic Contact Form Shown"),
                    ("diagnostic_email_submitted", "Diagnostic Email Submitted"),
                    ("diagnostic_contact_skipped", "Diagnostic Contact Skipped"),
                    ("diagnostic_results_viewed", "Diagnostic Results Viewed"),
                    ("diagnostic_restarted", "Diagnostic Restarted"),
                    ("diagnostic_abandoned", "Diagnostic Abandoned"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
